### PR TITLE
Add scheduler ordering and channel collision invariant tests

### PR DESCRIPTION
**Pull request by DominicBurkart**
## Summary
- Add 3 scheduler tests: event time ordering, same-time sequence ordering, schedule-and-advance integration
- Add 2 channel tests: no active transmissions after resolve, collision flag consistency
- 150 lines of new test coverage for previously untested invariants

## Test plan
- [ ] `cargo test --all-features` passes (52 tests including 5 new)
- [ ] Verify codecov patch coverage meets 100% target

### CODE REVIEW

File: src/channel.rs [hunk 1]
```diff
@@ -552,4 +552,74 @@ mod tests {
...
+        let mut ch2 = Channel::new();
+        let tx_a = make_tx(7, 868_100_000, 50_000);
+        let tx_b = make_tx(7, 868_100_000, 50_000);
+        ch2.begin_transmission(NodeId(10), &tx_a, 0);
+        ch2.begin_transmission(NodeId(11), &tx_b, 5_000);
+        ch2.resolve_at(55_000);
+        let delivered = ch2.deliver_to(55_000);
+        assert_eq!(
+            delivered.len(),
+            0,
```
Comment (DominicBurkart) [inline src/channel.rs:848]: **Blocking: `deliver_to` usage conflicts with PR #16.** This test calls `ch2.deliver_to(55_000)`, but PR #16 removes `deliver_to` entirely. If #16 merges first, this PR will not compile. Migrate to `drain_completed` and filter by `!collided` manually, or coordinate merge order explicitly.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: src/scheduler.rs [hunk 2]
```diff
@@ -715,6 +715,86 @@ mod tests {
...
+        sched2.run();
+        assert!(
+            sched2.current_time() <= 1_000_000,
+            "scheduler must not exceed end_time"
+        );
+        assert!(
+            sched2.current_time() >= 900_000,
+            "scheduler should have advanced to at least 900k"
+        );
+    }
```
Comment (DominicBurkart) [inline src/scheduler.rs]: **Blocking: duplicate tests.** The three scheduler tests in this file (`test_events_dequeue_in_time_order`, `test_same_time_events_ordered_by_sequence`, `test_schedule_and_advance`) are identical to tests also added in PR #21 and PR #17. Merging multiple PRs will cause duplicate-symbol compilation errors. One PR should own these tests; the others should drop them.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by DominicBurkart — COMMENTED** [review]
## Review: Add scheduler ordering and channel collision invariant tests

**Verdict: CHANGES NEEDED** (2 blocking cross-PR conflicts, 1 suggestion)

### Overall
The 5 new tests cover meaningful invariants: heap ordering by time, tie-breaking by sequence number, scheduler time advancement, channel resolution cleanup, and collision flag consistency. Test logic is correct and assertions are well-labeled.

### Blocking

1. **`deliver_to` conflict with PR #16.** `test_collision_state_consistency` calls `ch2.deliver_to()`, which PR #16 removes. If #16 merges first this PR breaks. Migrate to `drain_completed` + manual filter.

2. **Duplicate tests with PRs #17 and #21.** The three scheduler tests (`test_events_dequeue_in_time_order`, `test_same_time_events_ordered_by_sequence`, `test_schedule_and_advance`) are identical copies of tests also present in PR #17 and PR #21. Merging any two of these PRs will cause duplicate-symbol compilation errors. One PR should own these tests; the others should drop them.

### Non-blocking

3. `test_schedule_and_advance` conflates heap ordering verification (already covered by `test_events_dequeue_in_time_order`) with scheduler run-time advancement. Split for clearer failure diagnostics. The `>= 900_000` lower bound is loose -- consider computing expected final wake time from `PeriodicNode` parameters.

### CI Status
All 6 checks pass (Check, Test, Code Coverage, Cargo Deny, Autoformat, Security Audit).

---
_Generated by [Claude Code](https://claude.ai/code) via automated review_

---
_Generated by [Claude Code](https://claude.ai/code)_

File: src/channel.rs (hunk 1 above)
Comment (DominicBurkart) [reply src/channel.rs:848]: Addressed in commit bce62fe: switched the test from `ch2.deliver_to(55_000)` to `ch2.drain_completed()` filtered by `!collided`, so the test no longer depends on the `deliver_to` API that PR #16 removes. Equal-power collisions are still asserted not to be delivered.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: src/scheduler.rs (hunk 2 above)
Comment (DominicBurkart) [reply src/scheduler.rs]: Addressed in commit bce62fe: dropped `test_events_dequeue_in_time_order`, `test_same_time_events_ordered_by_sequence`, and `test_schedule_and_advance` from this PR so they no longer collide with PR #21 (PR #17 already merged and did not include these). Channel invariant tests in this PR remain.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by DominicBurkart — COMMENTED** [review]
## Review: Add scheduler ordering and channel collision invariant tests (latest commit 9830350)

**Verdict: LGTM** — all prior blocking issues are resolved; no new issues found.

---

### What changed since the first review

Both blocking issues flagged on 2026-03-31 have been addressed:

1. **`deliver_to` conflict (resolved).** `test_collision_state_consistency` no longer calls `ch2.deliver_to()`. It now uses `ch2.drain_completed()` filtered by `!collided`, eliminating the API dependency that PR #16 removes.

2. **Duplicate scheduler tests (resolved).** The three scheduler tests (`test_events_dequeue_in_time_order`, `test_same_time_events_ordered_by_sequence`, `test_schedule_and_advance`) have been dropped from this PR entirely. The current diff adds only two channel-level tests in `src/channel.rs`, avoiding duplicate-symbol conflicts with PR #21.

---

### Test-by-test assessment

**`test_no_active_after_resolve`**
- Creates 3 overlapping transmissions with distinct end times (40 k, 50 k, 100 k µs).
- Calls `resolve_at(50_000)` to settle two of them, then verifies `resolve_at(100_000)` returns exactly 1 event (tx3 still active) and `resolve_at(200_000)` returns 0.
- Logic is sound. The assertion messages are clear. Covers the invariant that `resolve_at` correctly drains ended transmissions and leaves ongoing ones in place.

**`test_collision_state_consistency`**
- Part 1: two equal-power transmissions on the same channel/frequency overlap. After `resolve_at` + `drain_completed`, both entries must have `collided = true` and `captured = false`. Correct — equal-power signals cannot capture each other.
- Part 2: builds a second channel with the same scenario and asserts that filtering out collided frames yields an empty delivery list. This directly tests that collided frames are not forwarded, which is the key safety invariant.
- Both assertions use descriptive failure messages with `sender` context. No issues.

---

### CI & coverage

All 6 checks pass on commit `9830350` (Check, Test, Code Coverage, Cargo Deny, Autoformat, Security Audit). Codecov reports 100% line coverage maintained — both new tests are fully exercised.

---

### Minor observations (non-blocking)

- The `resolve_time` variable in `test_no_active_after_resolve` is defined (`let resolve_time = 50_000;`) but not used — `ch.resolve_at(resolve_time)` is never called with it explicitly in the first call; the next call uses the literal `50_000` indirectly via the `resolve_at` at line that reads `ch.resolve_at(resolve_time)`. On closer reading: `ch.resolve_at(resolve_time)` **is** called (the return value is just discarded), so the variable is used. No dead-code warning expected; this is fine.
- The comment `// tx1 (end=50k) and tx2 (end=40k) resolved; tx3 (end=100k) still active.` is helpful for readers.

---

### Cross-PR status

| Prior concern | Status |
|---|---|
| `deliver_to` removed by PR #16 | Resolved — migrated to `drain_completed` |
| Duplicate scheduler tests (PRs #17, #21) | Resolved — scheduler tests dropped from this PR |

No outstanding cross-PR conflicts identified. This PR is ready for merge once the draft status is lifted and any remaining PR dependencies are settled.

---

_Generated by [Claude Code](https://claude.ai/code/session_016yCZ5prn7jKBMEjoH2WWuZ)_

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by DominicBurkart** [comment]
All blocking issues resolved: deliver_to() migrated to drain_completed() and duplicate scheduler tests dropped. All 6 CI checks pass with 100% Codecov coverage. Ready to open for review once the draft flag is lifted. https://claude.ai/code/session_016yCZ5prn7jKBMEjoH2WWuZ

---
_Generated by [Claude Code](https://claude.ai/code)_
